# Generated by Django 5.0.2 on 2024-07-19 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_alter_course_professor_alter_courseorder_course_and_more'),
        ('Products', '0004_alter_deal_product_alter_review_product_and_more'),
        ('Ranks', '0002_rank_color'),
        ('Users', '0005_delete_orphaned_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, related_name='userss', to='Users.badge'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_users', to='Courses.course'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked_products',
            field=models.ManyToManyField(blank=True, null=True, to='Products.product'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked_videos',
            field=models.ManyToManyField(blank=True, null=True, to='Courses.video'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ranks.rank'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
