# Generated by Django 5.0.2 on 2024-07-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_alter_course_professor_alter_courseorder_course_and_more'),
        ('Products', '0004_alter_deal_product_alter_review_product_and_more'),
        ('Users', '0006_alter_address_user_alter_customuser_badges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='badges',
            field=models.ManyToManyField(related_name='userss', to='Users.badge'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='enrolled_users', to='Courses.course'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked_products',
            field=models.ManyToManyField(to='Products.product'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked_videos',
            field=models.ManyToManyField(to='Courses.video'),
        ),
    ]
