# Generated by Django 5.0.2 on 2024-07-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_customuser_badges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pfp',
            field=models.ImageField(blank=True, default='default_avatar.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
