# Generated by Django 5.0.7 on 2024-07-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_address_user_alter_professor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pfp',
            field=models.ImageField(blank=True, default='default_avatar.webp', null=True, upload_to='profile_pics/'),
        ),
    ]
