# Generated by Django 5.0.7 on 2024-07-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_customuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pfp',
            field=models.ImageField(blank=True, default='default_avatar.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
