# Generated by Django 5.0.7 on 2024-07-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_remove_customuser_birth_date_alter_customuser_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pfp',
            field=models.ImageField(blank=True, default='default_avatar.webp', null=True, upload_to='profile_pics/'),
        ),
    ]
