# Generated by Django 5.0.7 on 2024-07-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_customuser_birth_date_alter_customuser_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
    ]
