# Generated by Django 5.0.7 on 2024-07-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_remove_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bought_course_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
