# Generated by Django 5.0.7 on 2024-08-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0011_vocal'),
        ('Users', '0018_customuser_bought_course_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_vocals',
            field=models.ManyToManyField(blank=True, null=True, to='Pages.vocal'),
        ),
    ]
