# Generated by Django 5.0.7 on 2024-10-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_customuser_first_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='role',
            field=models.TextField(default='Trading'),
        ),
    ]
