# Generated by Django 5.0.7 on 2024-11-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_professor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
