# Generated by Django 5.0.2 on 2024-06-26 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0002_initial'),
        ('Pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='home',
            name='featured_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.course'),
        ),
        migrations.AddField(
            model_name='onboardingoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Pages.onboardingquestion'),
        ),
        migrations.AddField(
            model_name='onboardingquestiontrack',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Pages.onboardingoption'),
        ),
        migrations.AddField(
            model_name='onboardingquestiontrack',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Pages.onboardingquestion'),
        ),
        migrations.AddField(
            model_name='onboardingtrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_boarding', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingquestiontrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Pages.onboardingtrack'),
        ),
        migrations.AddField(
            model_name='step',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Pages.quest'),
        ),
        migrations.AddField(
            model_name='userquestprogress',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pages.step'),
        ),
        migrations.AddField(
            model_name='userquestprogress',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.quest'),
        ),
        migrations.AddField(
            model_name='userquestprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
