# Generated by Django 5.0.2 on 2024-06-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingoption',
            name='image',
        ),
        migrations.RemoveField(
            model_name='onboardingoption',
            name='name',
        ),
        migrations.RemoveField(
            model_name='onboardingquestion',
            name='image',
        ),
        migrations.AddField(
            model_name='onboardingoption',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='on_boarding/'),
        ),
        migrations.AddField(
            model_name='onboardingoption',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='question_type',
            field=models.CharField(choices=[('table', 'Table'), ('images', 'Images')], default='images', max_length=50),
        ),
        migrations.AlterField(
            model_name='onboardingquestion',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
