# Generated by Django 5.0.2 on 2024-06-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredyoutubevideo',
            old_name='video_id',
            new_name='video_url',
        ),
    ]
