# Generated by Django 5.0.2 on 2024-06-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_dashboardlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
