# Generated by Django 5.0.2 on 2024-06-21 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_alter_dashboardlog_timestamp'),
        ('Users', '0002_remove_customuser_rank_customuser_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnBoardingTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_boarding', to='Users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='OnBoardingQuestionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=10000, null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Pages.onboardingoption')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Pages.onboardingtrack')),
            ],
        ),
    ]
