# Generated by Django 5.0.2 on 2024-06-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_onboardingtrack_onboardingquestiontrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingquestion',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
