# Generated by Django 5.0.2 on 2024-07-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_alter_feedback_user_alter_home_featured_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingquestiontrack',
            name='answer_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingquestion',
            name='question_type',
            field=models.CharField(choices=[('table', 'Table'), ('images', 'Images'), ('input', 'Input')], default='images', max_length=50),
        ),
    ]
