# Generated by Django 5.0.2 on 2024-07-19 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_onboardingquestiontrack_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingoption',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='Pages.onboardingquestion'),
        ),
    ]
