# Generated by Django 5.0.2 on 2024-06-21 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_onboardingquestion_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingquestiontrack',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Pages.onboardingoption'),
        ),
        migrations.AlterField(
            model_name='onboardingquestiontrack',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Pages.onboardingquestion'),
        ),
    ]
