# Generated by Django 5.0.2 on 2024-07-19 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_alter_onboardingoption_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingquestiontrack',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='Pages.onboardingoption'),
        ),
        migrations.AlterField(
            model_name='onboardingquestiontrack',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='Pages.onboardingquestion'),
        ),
        migrations.AlterField(
            model_name='onboardingquestiontrack',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='Pages.onboardingtrack'),
        ),
    ]
