# Generated by Django 5.0.2 on 2024-07-19 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0008_alter_onboardingquestiontrack_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingquestiontrack',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='onboardingquestiontrack',
            name='input_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingquestiontrack',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pages.onboardingoption'),
        ),
        migrations.AlterField(
            model_name='onboardingquestiontrack',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pages.onboardingquestion'),
        ),
        migrations.AlterField(
            model_name='onboardingquestiontrack',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pages.onboardingtrack'),
        ),
    ]
