# Generated by Django 5.0.7 on 2024-08-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0010_alter_feedback_user_alter_home_featured_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('students_only', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='vocals/')),
            ],
        ),
    ]
