# Generated by Django 5.0.7 on 2024-09-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0012_userdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('checked', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
