# Generated by Django 5.0.7 on 2024-09-18 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0016_userdailyactivity_delete_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='userdailyactivity',
            name='total_time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
