# Generated by Django 5.0.7 on 2024-09-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0017_dailylesson_alter_userdailyactivity_total_time_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='generalCheckRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
