# Generated by Django 5.0.7 on 2024-09-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0018_generalcheckrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vocmp3'),
        ),
    ]
