# Generated by Django 5.0.7 on 2024-10-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0019_vocal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
