# Generated by Django 5.0.7 on 2024-10-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0020_bookorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='state',
            field=models.TextField(null=True),
        ),
    ]
