# Generated by Django 5.0.2 on 2024-08-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePublicVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_user_ip', models.CharField(max_length=25)),
                ('visit_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
