# Generated by Django 5.0.7 on 2024-09-10 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customTheme', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
