# Generated by Django 5.0.2 on 2024-06-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('none', 'None'), ('tshirt', 'T-Shirt'), ('cap', 'Cap'), ('cup', 'Cup')], default='regular', max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
