# Generated by Django 5.0.2 on 2024-06-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vimeo_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
