# Generated by Django 5.0.2 on 2024-06-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='requierment',
            field=models.CharField(choices=[('None', 'None'), ('previous', 'Previous'), ('hard', 'Hard Close')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='requierment',
            field=models.CharField(choices=[('None', 'None'), ('previous', 'Previous'), ('hard', 'Hard Close')], default='None', max_length=100),
        ),
    ]
