# Generated by Django 5.0.2 on 2024-06-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_remove_quiz_option1_remove_quiz_option1_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='open_videos',
            field=models.BooleanField(default=False),
        ),
    ]
