# Generated by Django 5.0.2 on 2024-06-21 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_module_requierment_alter_video_requierment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('tel', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('tba', 'Transfer Bank Account (R.I.B - Preferred)'), ('e-dinar', 'E-Dinar'), ('paypal', 'Paypal'), ('zelle', 'Zelle'), ('cashapp', 'Cash App'), ('crypto', 'Crypto'), ('wise', 'Wise'), ('venmo', 'Venmo')], max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Courses.course')),
            ],
        ),
    ]
