# Generated by Django 5.0.2 on 2024-06-09 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_course_url_title_alter_course_discount_price_and_more'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercourseprogression', to='Users.customuser'),
        ),
    ]
