# Generated by Django 5.0.2 on 2024-06-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_courseorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorder',
            old_name='city',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='courseorder',
            name='state',
        ),
    ]
