# Generated by Django 5.0.2 on 2024-07-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_courseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='url_title',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
