# Generated by Django 5.0.2 on 2024-06-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_usercourseprogress_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='requierment',
            field=models.CharField(choices=[('None', 'None'), ('previous', 'Previous Video')], default='None', max_length=100),
        ),
    ]
