# Generated by Django 5.0.2 on 2024-07-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_level_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='url_title',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
