# Generated by Django 5.0.2 on 2024-06-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_module_requierment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='finished',
        ),
        migrations.AddField(
            model_name='video',
            name='requierment',
            field=models.CharField(choices=[('None', 'None'), ('previous', 'Previous Video')], default='None', max_length=100),
        ),
    ]
