# Generated by Django 5.0.2 on 2024-06-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_rename_country_courseorder_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='country',
            field=models.CharField(default='Tunisia', max_length=100),
            preserve_default=False,
        ),
    ]
