# Generated by Django 5.0.2 on 2024-06-21 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_courseorder_country'),
        ('Users', '0002_remove_customuser_rank_customuser_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_orders', to='Users.customuser'),
        ),
    ]
