# Generated by Django 5.0.2 on 2024-07-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0008_alter_course_professor_alter_courseorder_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Trading', 'Trading'), ('Development', 'Development'), ('Design', 'Design UI / UX'), ('Data Science', 'Data Science'), ('Marketing', 'Marketing')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='index',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='index',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
