# Generated by Django 5.0.2 on 2024-07-23 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0009_alter_course_category_alter_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='Courses.video'),
        ),
    ]
