# Generated by Django 5.0.2 on 2024-07-23 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0010_alter_quiz_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizoption',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='Courses.quiz'),
        ),
    ]
