# Generated by Django 5.0.2 on 2024-07-23 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0011_alter_quizoption_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizoption',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Courses.quiz'),
        ),
    ]
