# Generated by Django 5.0.7 on 2024-07-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0013_alter_course_professor_alter_courseorder_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='index',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='requierment',
            field=models.CharField(choices=[('None', 'None'), ('previous', 'Previous'), ('hard', 'Hard Close')], default='None', max_length=100),
        ),
    ]
