# Generated by Django 5.0.7 on 2024-08-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0014_level_index_level_requierment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quizzes_images/'),
        ),
    ]
