# Generated by Django 5.0.7 on 2024-08-07 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0015_quiz_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='video_checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkpointed_videos', to='Courses.video'),
        ),
    ]
