# Generated by Django 5.0.7 on 2024-08-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0016_usercourseprogress_video_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url_title',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
