# Generated by Django 5.0.7 on 2024-09-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0018_userlevelcheckpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mini_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
