# Generated by Django 5.0.7 on 2024-09-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0019_course_mini_description_course_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevelcheckpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
