# Generated by Django 5.0.7 on 2024-09-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0020_userlevelcheckpoint_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
