# Generated by Django 5.0.7 on 2024-09-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0021_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fake_enrollment',
            field=models.IntegerField(default=0),
        ),
    ]
