# Generated by Django 5.0.7 on 2024-09-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0022_course_fake_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='langing_img',
            field=models.ImageField(blank=True, null=True, upload_to='li'),
        ),
    ]
