# Generated by Django 5.0.7 on 2024-09-29 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0024_course_mini_langing_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='langing_img',
            new_name='landing_img',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='mini_langing_img',
            new_name='mini_landing_img',
        ),
    ]
