# Generated by Django 5.0.7 on 2024-10-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0025_rename_langing_img_course_landing_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.TextField(default='fa-graduation-cap'),
        ),
    ]
