# Generated by Django 5.0.7 on 2024-10-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0026_course_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_count',
            field=models.IntegerField(default=0),
        ),
    ]
