# Generated by Django 5.0.7 on 2024-10-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0027_course_video_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_count',
        ),
    ]
