# Generated by Django 5.0.7 on 2024-10-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0028_remove_course_video_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_count',
            field=models.IntegerField(default=0),
        ),
    ]
