# Generated by Django 5.0.7 on 2024-12-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0030_levelfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
