# Generated by Django 5.0.2 on 2024-07-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrivateSessions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatesessionrequest',
            name='selected_professor',
            field=models.CharField(blank=True, choices=[('0', 'az'), ('1', '1 zz'), ('2', '1H 30zz Minutes')], max_length=150, null=True),
        ),
    ]
