# Generated by Django 5.0.2 on 2024-07-19 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0008_alter_course_professor_alter_courseorder_course_and_more'),
        ('PrivateSessions', '0004_alter_privatesession_cours_and_more'),
        ('Users', '0007_alter_customuser_badges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatesession',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_sessions', to='Courses.course'),
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professor_private_sessions', to='Users.professor'),
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_private_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
