# Generated by Django 5.0.7 on 2024-08-23 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrivateSessions', '0006_alter_privatesession_cours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatesession',
            name='student',
        ),
    ]
